version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - npm install
  
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Preparing application..."
      - mkdir -p logs
      - mkdir -p cache
      - mkdir -p visualizations
      - mkdir -p visualizaciones
      - mkdir -p logos
  
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - app.py
    - dashboard.py
    - requirements.txt
    - package.json
    - server.js
    - nba_team_complete_stats_2024_25.csv
    - buildspec.yml
    - amplify.yml
    - Procfile
    - "**/*"
  discard-paths: no 