branch-defaults:
  main:
    environment: nba-stats-analyzer-env
global:
  application_name: nba-stats-analyzer
  default_platform: Python 3.9
  default_region: us-east-1
  profile: default
  sc: git 